name: phomem
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.2.1
  uuid: ^4.4.0
  image_card: ^0.0.4
  flutter_form_builder: ^9.2.1
  image_picker: ^1.1.1
  carousel_slider: ^4.2.1
  json_annotation: ^4.9.0
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  i18n_extension: ^11.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - icons/LogoPhoMem.png